root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/server ./cmd/server"
bin = "./tmp/server"
full_bin = "./tmp/server"
include_ext = ["go", "mod", "sum", "toml"]
exclude_dir = ["tmp", "bin", "vendor", ".git"]
delay = 200
stop_on_error = true
send_interrupt = true
kill_delay = "500ms"

[log]
time = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"
